
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        arch: 'clang_64'

    - name: Build application
      run: |
        qmake draw.pro
        make

    - name: Run tests
      run: |
        export QT_PLUGIN_PATH=$QT_INSTALL_DIR/plugins
        export QML2_IMPORT_PATH=$QT_INSTALL_DIR/qml
        qmltestrunner -input tests/tst_ColorPalettePopup.qml

